apiVersion: v1
kind: ConfigMap
metadata:
  name: airborne-management-service-config
data:
  PORT: "3000"
  DB_USERNAME: "airborne_user"
  DB_NAME: "airborne"
  DB_HOST: "dpg-d64mj94r85hc73bvbfu0-a.singapore-postgres.render.com"